# config-.yaml
envoy_path: "/home/matth/envoy"       # Envoy 可执行文件路径
server_list:                             # Etcd 集群所有节点
  - "34.96.131.245:2379"
  - "34.141.236.188:2379"
server_ip: "34.96.131.245"                    # 当前节点 IP
data_dir: "/home/matth/etcd"                # Etcd 数据目录
#name: "etcd-1"                            # 当前节点名字

node:
  provider: "gcp"        # gcp | aws | azure | vultr | digitalocean | onprem
  continent: "Asia"      # ONLY field used for bandwidth / cost query
  country: "Asia"          # 可选，用于日志/解释/未来扩展
  city: "asia-northeast1-b"          # 可选，用于日志/解释/未来扩展

  ip:
    private: "10.170.0.2"  # 内网 IP
    public: "34.96.131.245" # 公网 IP 作为hostname

  # 节点相关配置结束

proxy:
  ips:
    - "34.96.131.245"

gcp:
  projectID: "civil-honor-480405-e0"      # 替换为你的 GCP 项目 ID
  zone: "asia-northeast1-b"                   # 机房
  vmPrefix: "scaling-vm-"                     # VM 名称前缀（不是具体名字）
  credFile: "/home/matth/civil-honor-480405-e0-e62b994bbc27.json"  # GCP 凭证文件路径